use_frameworks!

target 'MSGridKit_Example' do
  pod 'MSGridKit', :path => '../'

  target 'MSGridKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
